apiVersion: v1
kind: Service
metadata:
  name: tomcal-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: tomcal
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcal-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: tomcal
  template:
    metadata:
      labels:
        app: tomcal
    spec:
      containers:
      - name: tomcatcal
        image: ravva123/raveena:tomadd
        ports:
        -containerPort: 8080
